CD: setup of test.json and response verification

diff --git a/.github/actions/aml-endpoint-test/action.yaml b/.github/actions/aml-endpoint-test/action.yaml
--- a/.github/actions/aml-endpoint-test/action.yaml
+++ b/.github/actions/aml-endpoint-test/action.yaml
@@ -43,4 +43,10 @@ runs:
           TEST_DEPLOYMENT_NAME='blue'
         fi
 
-        az ml online-endpoint invoke -n $ENDPOINT_NAME --deployment $TEST_DEPLOYMENT_NAME --request-file ${{ inputs.requestFile }}
+        TEST_RESPONSE=$(az ml online-endpoint invoke -n $ENDPOINT_NAME --deployment $TEST_DEPLOYMENT_NAME --request-file ${{ inputs.requestFile }})
+        if [ $TEST_RESPONSE == "\"[8.451999999999995, 25.986400000000007]\"" ]; then
+          echo "Test passed"
+        else
+          echo "Test failed"
+          exit 1
+        fi
